version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: windsurf-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-password}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - windsurf-network

  neo4j:
    image: neo4j:5.5
    container_name: windsurf-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH:-neo4j/password}
      NEO4J_dbms_logs_debug_level: ${NEO4J_LOG_LEVEL:-INFO}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - windsurf-network

  arangodb:
    image: arangodb:3.10.4
    environment:
      - ARANGO_ROOT_PASSWORD=habitat
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    restart: unless-stopped

volumes:
  mongodb_data:
  neo4j_data:
  arangodb_data:
  arangodb_apps:

networks:
  windsurf-network:
    name: windsurf-network
